name: benchmark
on:
  push:
    branches:
      - master
env:
  CI: true
permissions:
  contents: write
jobs:
  benchmark:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Run Benchmark
        run: cd examples/benchmark && node benchmark.js | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20.4
        with:
          name: HonKit benchmark
          tool: 'benchmarkjs'
          output-file-path: examples/benchmark/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@azu'
