name: test
on:
  push:
    branches:
      - master
      - main
  pull_request:
env:
  CI: true
  NODE_VERSION: 24
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 20, 22, 24 ]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run lint && pnpm test
      - name: Run E2E
        run: pnpm run build
        working-directory: examples/benchmark

  docker-image:
    name: "Build docker image and generate pdf"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Build docker image
        run: docker buildx build -t testing --build-arg NODE_VERSION=${NODE_VERSION} ./docker
      - name: Generate pdf
        run: docker run -v `pwd`/examples/book:/work -w /work --rm testing honkit pdf
